# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is commited to
# your git repository.
cache:
  paths:
    - vendor/
    - node_modules/
    - bower_components/

# Before Tests
before_script:
  - bash docker_setup.sh > /dev/null

# Services
services:
  - mysql:latest

# Variables
variables:
  WITH_XDEBUG: "1"
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_DATABASE: homestead
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret
  COMPOSER_HOME: /cache/composer

# Stages
stages:
  - test

# PHP 8.1 FPM
php:8.1-fpm:
  image: php:8.1-fpm
  stage: test
  script:
    - php -v
    - php vendor/bin/phpunit --colors --debug --coverage-text