openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/sendOtp:
    post:
      summary: 'Send OTP'
      operationId: sendOTP
      description: 'Send SMS OTP to phone number'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/x-www-form-urlencoded
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'OTP Sent!'
                properties:
                  message:
                    type: string
                    example: 'OTP Sent!'
        422:
          description: 'Invalid Form Fields'
          content:
            text/plain:
              schema:
                type: string
                example: '{"errors": ["country_code": ["The Country COde field is required."], "phone_no": ["The Phone No field is required."] ]}'
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                country_code:
                  type: string
                  description: "The country code of user's phone number."
                  example: '60'
                phone_no:
                  type: string
                  description: 'The Phone No of the user.'
                  example: '1234567890'
              required:
                - country_code
                - phone_no
      security: []
  /api/v1/verifyOtp:
    post:
      summary: 'Verify OTP'
      operationId: verifyOTP
      description: 'Login user into the system with OTP'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/x-www-form-urlencoded
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            text/plain:
              schema:
                type: string
                example: "{\n \"user\": {\n    id: 1,\n    name: \"John Smith\"\n },\n \"token\": \"AuthenticationTokenHere\"\n}"
        401:
          description: 'Invalid Login details'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Invalid login details'
                properties:
                  message:
                    type: string
                    example: 'Invalid login details'
        422:
          description: 'Invalid Form Fields'
          content:
            text/plain:
              schema:
                type: string
                example: '{"errors": ["country_code": ["The Country COde field is required."], "phone_no": ["The Phone No field is required."] ]}'
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                country_code:
                  type: string
                  description: "The country code of user's phone number."
                  example: '60'
                phone_no:
                  type: string
                  description: 'The Phone No of the user.'
                  example: '1234567890'
                otp:
                  type: string
                  description: "The OTP sent to user's phone number."
                  example: '123456'
              required:
                - country_code
                - phone_no
                - otp
      security: []
  /api/v1/loginWithPassword:
    post:
      summary: 'Login with Password'
      operationId: loginWithPassword
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: 'Accept:'
          description: ''
          example: application/x-www-form-urlencoded
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  user: {  }
                  token: auth_token
                properties:
                  user:
                    type: object
                    properties: []
                  token:
                    type: string
                    example: auth_token
        401:
          description: 'Invalid Credentials'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Invalid Credentials'
                properties:
                  message:
                    type: string
                    example: 'Invalid Credentials'
        422:
          description: 'Invalid Form Fields'
          content:
            text/plain:
              schema:
                type: string
                example: '{"errors": ["country_code": ["The Country COde field is required."], "phone_no": ["The Phone No field is required."] ]}'
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                country_code:
                  type: string
                  description: 'Country code of phone number.'
                  example: '60'
                phone_no:
                  type: string
                  description: 'Phone number.'
                  example: '1234567890'
                password:
                  type: string
                  description: Password.
                  example: abcd1234
              required:
                - country_code
                - phone_no
                - password
      security: []
  /api/v1/register/otp:
    post:
      summary: 'Register with OTP'
      operationId: registerWithOTP
      description: 'Register user with OTP'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/x-www-form-urlencoded
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            text/plain:
              schema:
                type: string
                example: "{\n \"user\": {\n    id: 1,\n    name: \"John Smith\"\n },\n \"token\": \"AuthenticationTokenHere\"\n}"
        422:
          description: 'Invalid Form Fields'
          content:
            text/plain:
              schema:
                type: string
                example: '{"errors": ["country_code": ["The Country COde field is required."], "phone_no": ["The Phone No field is required."] ]}'
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                country_code:
                  type: string
                  description: "The country code of user's phone number."
                  example: '60'
                phone_no:
                  type: string
                  description: 'The Phone No of the user.'
                  example: '1234567890'
                otp:
                  type: string
                  description: "The OTP sent to user's phone number."
                  example: '123456'
                name:
                  type: string
                  description: 'The name of the use.'
                  example: 'John Smith'
                password:
                  type: string
                  description: 'The password of the user.'
                  example: abcd1234
              required:
                - country_code
                - phone_no
                - otp
                - name
                - password
      security: []
  /api/v1/logout:
    post:
      summary: Logout
      operationId: logout
      description: 'Log User Out and destroy any active tokens of user'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/x-www-form-urlencoded
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Logged Out'
                properties:
                  message:
                    type: string
                    example: 'Logged Out'
        401:
          description: 'Access Denied'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Access Denied'
                properties:
                  message:
                    type: string
                    example: 'Access Denied'
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
